# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89a49fcb94335391f8b4237eb18793ba149c350952329e1118271905a5e8e8e9625cabadbc69c35f759580e62d85c29760482e6fee48535f38d3f44eaa8d01a5

test:
  secret_key_base: 461e05f6b07052b1f5d3d4e27ea9722c5b8c73b4f74b7c89867b740e489647e39e187e9ddc8c02cbb155243f12c5c19bc62fe81bc13830aeebaa6bbc58576c9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
